// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgnM8HkLrSttTkdY0ju8QWt49mj6dGoF4',
    appId: '1:403346297857:web:849d2bdb3b59f77c7e1c00',
    messagingSenderId: '403346297857',
    projectId: 'spotoolfy',
    authDomain: 'spotoolfy.firebaseapp.com',
    storageBucket: 'spotoolfy.firebasestorage.app',
    measurementId: 'G-8MD31NR3LE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNX6BBqEfF_DTsS5GlSS8rlehVQKEyTCE',
    appId: '1:403346297857:android:568c6d27c25d7d717e1c00',
    messagingSenderId: '403346297857',
    projectId: 'spotoolfy',
    storageBucket: 'spotoolfy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6ju6eFNpUaIsyLLxk4FJymv4-WaDS8dE',
    appId: '1:403346297857:ios:6a764bb47a35d3d07e1c00',
    messagingSenderId: '403346297857',
    projectId: 'spotoolfy',
    storageBucket: 'spotoolfy.firebasestorage.app',
    androidClientId: '403346297857-6tbab6rvvb3851kv7fuucp121o9gk04o.apps.googleusercontent.com',
    iosClientId: '403346297857-fuu90sg1tcbe458vri6aleo6i5f9sjkt.apps.googleusercontent.com',
    iosBundleId: 'com.gojyuplusone.spotoolfy.spotoolfyFlutter',
  );

}